# Generated by Django 4.2.6 on 2023-10-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangofc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='img',
            field=models.ImageField(default=0, height_field=200, upload_to='', width_field=100),
        ),
    ]
